[programs.devnet]
split = "4tzDAD5KLntPhT8t3gjqs85vsT5aguZTNCoeRvKkt5zr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./solwal/id.json"

[scripts]
test = "node tests/split.js"
